services:
  php-test:
    build:
      context: ./test
    container_name: php-test-fpm
    restart: unless-stopped
    ports:
      - "9099:9000"
    volumes:
      - ./test/test-php.ini:/etc/php/7.3/fpm/php.ini
      - ./test/test-php.ini:/etc/php/7.3/cli/php.ini
      - ./test/test-php-fpm.conf:/etc/php/7.3/fpm/pool.d/z-test.conf
      - /var/www:/var/www
      - ./test-spreadsheet.php:/var/www/test-spreadsheet.php
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
