version: '3.8'

services:
  php82:
    build:
      context: ./php82
    container_name: php82-fpm
    restart: unless-stopped
    ports:
      - "9082:9000"
    volumes:
      - ./php82/php.ini:/etc/php/8.2/fpm/php.ini
      - ./php82/php.ini:/etc/php/8.2/cli/php.ini
      - ./php82/php-fpm.conf:/etc/php/8.2/fpm/pool.d/z-overrides.conf
      - /var/www:/var/www
