services:
  php84:
    build:
      context: ./php84
    container_name: php84-fpm
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    ports:
      - "9084:9000"
    extra_hosts:
      - "socket.al-ameen.lo:host-gateway"
      - "api.al-ameen.lo:host-gateway"
      - "al-ameen.lo:host-gateway"
    volumes:
      - ./php84/php.ini:/etc/php/8.4/fpm/php.ini
      - ./php84/php.ini:/etc/php/8.4/cli/php.ini
      - ./php84/php-fpm.conf:/etc/php/8.4/fpm/pool.d/z-overrides.conf
      - ${HOST_WWW_PATH:-/var/www}:/var/www
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
