services:
  php74:
    build:
      context: ./php74
    container_name: php74-fpm
    restart: unless-stopped
    ports:
      - "9074:9000"
    volumes:
      - ./php74/php.ini:/etc/php/7.4/fpm/php.ini
      - ./php74/php.ini:/etc/php/7.4/cli/php.ini
      - ./php74/php-fpm.conf:/etc/php/7.4/fpm/pool.d/z-overrides.conf
      - /var/www:/var/www
