server {
    server_name portal.al-ameen.in;

    root /var/www/al-ameen.in;

    access_log /var/log/nginx/al-ameen.in-access.log;
    error_log /var/log/nginx/al-ameen.in-error.log error;
    index index.html index.htm index.php;

    ## Compression
    gzip              on;
    gzip_buffers      16 8k;
    gzip_comp_level   4;
    gzip_http_version 1.0;
    gzip_min_length   1280;
    gzip_types        text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript image/x-icon image/bmp;
    gzip_vary         on;

    client_max_body_size 24000M;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;

        # Handle 404 errors by redirecting to index.php
        error_page 404 = /index.php;

        # Prevent caching
        add_header Cache-Control "no-cache, no-store, must-revalidate, private";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # PHP 8.0 FPM Socket
        fastcgi_pass 127.0.0.1:9080;
        fastcgi_index index.php;
        include fastcgi.conf;

        # Prevent caching
        add_header Cache-Control "no-cache, no-store, must-revalidate, private";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    listen 80;
    etag off;
}
